### ISSUE TITLE
Not source code

### ISSUE THREAD

**Issue by ghost** [XatzClient/PenisESP#1]
This is clearly a decompilation, not the actual source code, as shown by the variable names and GL flags

**Comment by Napoleon-x** [comment]
This is just the code for the module for our hacked client, it was from the actual source not decompiled, our hacked client uses mcp and isn't one of those mod clients

**Comment by ghost** [comment]
https://github.com/XatzClient/PenisESP/blob/df0966ad5139cf7835c6276534101042e367e32c/PenisESP.java#L120

Yes, I totally believe that this is from an actual source because you have memorised all the GL flags as ints rather than using the enums

**Comment by Napoleon-x** [comment]
> https://github.com/XatzClient/PenisESP/blob/df0966ad5139cf7835c6276534101042e367e32c/PenisESP.java#L120
> 
> Yes, I totally believe that this is from an actual source because you have memorised all the GL flags as ints rather than using the enums

Idk if you are trolling or you don't know how mcp clients work?

**Comment by ghost** [comment]
Are you seriously trying to tell me that your MCP workspace has the `GL11` class, but the enums are missing from it...

The `2896` integer I referenced earlier is the GL flag `GL_LIGHTNING`.
http://legacy.lwjgl.org/javadoc/org/lwjgl/opengl/GL11.html#GL_LIGHTING

**Comment by Napoleon-x** [comment]
Idk what you are on about but I do know that this is just a module from my client

**Comment by ghost** [comment]
Minecraft's OpenGL works via flags, setting up a stack and different filters and blah blah it's quite confusing.

Anyway, this code, at least the ESP part, originated from a decompilation, it may not have been you, it may not have been whoever you copied from, but it is from a decomp.

**Comment by Napoleon-x** [comment]
Ok, Idk what the point of this issue is, I will close now and probably work on my 1.8 client or something, good bye
